### ISSUE TITLE
[Vue warn]: Error in v-on handler: "TypeError: Class constructor Doc cannot be invoked without 'new'"

### ISSUE THREAD

**Issue by kawamataryo** [1amageek/ballcap.ts#4]
Hi. Thank you for creating a very useful library.
I want to use this library, but I am troubled with errors.

## Description
Error occurs when writing document.

```
[Vue warn]: Error in v-on handler: "TypeError: Class constructor Doc cannot be invoked without 'new'"
```

This error occurred here.
https://github.com/kawamataryo/try-ballcap/blob/master/src/components/tryBallcapp.vue#L60

## Screen shot
![スクリーンショット 2019-07-07 7 12 56](https://user-images.githubusercontent.com/11070996/60761675-5a26cf00-a088-11e9-9f93-ca787a27ad38.png)

##  Environment
Vue CLI 3 Project.

* vue v2.6.1
* typescript v3.4.3
* ballcap v0.4.1
* firebase 6.2.4

My repository is here.
https://github.com/kawamataryo/try-ballcap

**Comment by 1amageek** [comment]
@kawamataryo 

Thank you for your message.
This error is caused by babel.

Remove babel from package.json and run `npm install -d`.

```JSON
{
  "name": "try-ballcap",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@1amageek/ballcap": "^0.4.1",
    "core-js": "^2.6.5",
    "firebase": "^6.2.4",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-property-decorator": "^8.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-typescript": "^3.9.0",
    "@vue/cli-service": "^3.9.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "typescript": "^3.4.3",
    "vue-template-compiler": "^2.6.10"
  }
}

```

**Comment by kawamataryo** [comment]
@1amageek 

Thank you for your prompt reply.
My problem was resolved.

May I ask additional questions?
The same problem occurs When the target of tsconfig.json is set to es5.
（Does not occur when "esnext" or "es2015".）

```tsconfig.json
{
  "compilerOptions": {
    "target": "es5", 
...
```

Does this library not support  transpiling  es5 ?

**Comment by 1amageek** [comment]
@kawamataryo Please use es6

**Comment by kawamataryo** [comment]
OK. Thank you.
